server.port=8081
spring.datasource.url=jdbc:postgresql://pg-17502ad9-sachinguptadec03-44d7.a.aivencloud.com:20315/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=9fK8xL2pQw7zN3vB1mXcR5tY8uHjK4sD
jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operations-sort=method
springdoc.swagger-ui.tags-sort=name